[tools]
rojo = "rojo-rbx/rojo@7.6.1"
selene = "Kampfkarren/selene@0.30.0"
stylua = "JohnnyMorganz/stylua@2.3.1"
wally = "UpliftGames/wally@0.3.2"
run-in-roblox = "rojo-rbx/run-in-roblox@0.3.0"
lune = "lune-org/lune@0.10.4"
darklua = "seaofvoices/darklua@0.18.0"
