[package]
name = "usergenerated/mcp-studio-plugin"
version = "0.1.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
msgpack-luau = "cipharius/msgpack-luau@0.3.0"

[dev-dependencies]
Jest = "jsdotlua/jest@3.10.0"
JestGlobals = "jsdotlua/jest-globals@3.10.0"
